columns:
  main:
    width: 2/3
    sections:
      meta:
        type: fields
        fields:
          intro:
            type: textarea
            size: tiny
            help: Large text under page title

          contentBlocks:
            extends: fields/blocks-field

  sidebar:
    width: 1/3
    sections:
      meta2:
        type: fields
        fields:
          background:
            translate: false
            type: radio
            default: performances
            options:
              performances: Performances
              experiences: Experiences

      pages:
        label: Subpages
        type: pages
        create:
          - default-subpage

      files:
        type: files
        limit: 120
        sortBy: filename asc
